# Generated by Django 5.0.6 on 2024-06-04 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmenttype',
            name='type_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
