# Generated by Django 5.0.6 on 2024-06-04 09:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0002_alter_apartmenttype_type_name'),
        ('country', '0007_alter_cityphotos_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Создан'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apartment',
            name='sleeping_places',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='apartment',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлен'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='address',
            field=models.CharField(max_length=200, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='country.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='apartment.apartmenttype', verbose_name='Тип апартаментов'),
        ),
        migrations.AlterField(
            model_name='apartmenttype',
            name='type_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Тип апартаментов'),
        ),
    ]
