# Generated by Django 5.0.6 on 2024-06-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0003_apartment_created_apartment_sleeping_places_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='sleeping_places',
            field=models.IntegerField(default=1, verbose_name='Спальных мест'),
        ),
    ]
