# Generated by Django 5.0.6 on 2024-06-05 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0004_alter_apartment_sleeping_places'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='apartments/', verbose_name='Фото апартаментов')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='apartment.apartment', verbose_name='Апартаменты')),
            ],
            options={
                'verbose_name': 'Фото апартаментов',
                'verbose_name_plural': 'Фото апартаментов',
            },
        ),
    ]
