# Generated by Django 5.0.6 on 2024-06-19 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0006_apartment_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupApartmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=50)),
                ('descriptions', models.TextField(blank=True, null=True, verbose_name='Описание группы')),
            ],
            options={
                'verbose_name': 'Группа видов арендного жилья',
                'verbose_name_plural': 'Группы видов арендного жилья',
            },
        ),
        migrations.AddField(
            model_name='apartmenttype',
            name='group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='apartment.groupapartmenttype', verbose_name='Группа типов апартаментов'),
        ),
    ]
