# Generated by Django 5.0.6 on 2024-06-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0007_groupapartmenttype_apartmenttype_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupapartmenttype',
            name='short_info',
            field=models.CharField(default=' ', max_length=70),
        ),
    ]
