# Generated by Django 5.0.6 on 2024-06-25 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0013_alter_apartment_landlord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentphoto',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartmentphoto_set', to='apartment.apartment', verbose_name='Апартаменты'),
        ),
    ]
