# Generated by Django 5.0.6 on 2024-06-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0016_remove_apartment_address_apartment_number_block_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='count_floor',
            field=models.IntegerField(default=1, verbose_name='Количество этажей'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='count_room',
            field=models.IntegerField(default=1, verbose_name='Количество комнат'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='elevator',
            field=models.BooleanField(default=False, verbose_name='Наличие лифта'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='number_floor',
            field=models.IntegerField(default=1, verbose_name='Этаж'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='square',
            field=models.CharField(default=1, max_length=5, verbose_name='Площадь апартаментов'),
        ),
    ]
