# Generated by Django 5.0.6 on 2024-07-01 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0018_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_set', to='apartment.apartment', verbose_name='Апартаменты'),
        ),
    ]
