# Generated by Django 5.0.6 on 2024-08-07 13:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0021_comment_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Комментарий апартаментов', 'verbose_name_plural': 'Комментарии апартаментов'},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name': 'Оценка апартаментов', 'verbose_name_plural': 'Оценки апартаментов'},
        ),
        migrations.AddField(
            model_name='booking',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Забронировано'),
            preserve_default=False,
        ),
    ]
