# Generated by Django 5.0.6 on 2024-08-08 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0022_alter_comment_options_alter_rating_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupapartmenttype',
            name='group_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='groupapartmenttype',
            name='short_info',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
