# Generated by Django 5.0.6 on 2024-08-09 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0023_alter_groupapartmenttype_group_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='count_floor',
            field=models.IntegerField(default=1, null=True, verbose_name='Количество этажей'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='number_floor',
            field=models.IntegerField(default=1, null=True, verbose_name='Этаж'),
        ),
    ]
