# Generated by Django 5.0.6 on 2024-05-30 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.CharField(default='user@example.com', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.CharField(default='user', max_length=50),
        ),
    ]
