# Generated by Django 5.0.6 on 2024-06-18 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userprofile_email_userprofile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='firstname',
            field=models.CharField(default='user', max_length=50, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='secondname',
            field=models.CharField(default='user', max_length=50, verbose_name='Фамилия'),
        ),
    ]
