# Generated by Django 5.0.6 on 2024-06-18 10:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userprofile_firstname_userprofile_secondname'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='genders',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1), blank=True, null=True, size=None),
        ),
    ]
