# Generated by Django 5.0.6 on 2024-08-07 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_userprofile_genders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='user/noimage.png', null=True, upload_to='profile_image/', verbose_name='Фото профиля'),
        ),
    ]
