# Generated by Django 5.0.6 on 2024-05-27 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='link',
            field=models.CharField(default='/', max_length=100),
        ),
    ]
