# Generated by Django 5.0.6 on 2024-05-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0002_menuitem_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='VocationIdeas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('info', models.TextField(blank=True, null=True, verbose_name='Информация')),
                ('image', models.ImageField(blank=True, null=True, upload_to='places/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Идея для отпуска',
                'verbose_name_plural': 'Идеи для отпуска',
            },
        ),
    ]
