# Generated by Django 5.0.6 on 2024-05-31 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0003_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='countries/', verbose_name='Изображение'),
        ),
    ]
