# Generated by Django 5.0.6 on 2024-06-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0004_country_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cities/', verbose_name='Изображение'),
        ),
    ]
