# Generated by Django 5.0.6 on 2024-06-04 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0006_cityphotos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityphotos',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city', to='country.city'),
        ),
    ]
